apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  labels:
    app: flask1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      containers:
      - name: myapp1
        image: app1:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      restartPolicy: Always
